<?php
echo "Enrolled Students for this course<br><br>";
$a = $_GET['id'];
if(isset($_GET['to_remove']))
{
    $b=$_GET['to_remove'];
require_once('dbconnect.php');
//echo "delete from enrolled_details where course_id='$a' and id_no='$b'";
$result = mysql_query("delete from enrolled_details where course_id='$a' and id_no='$b'") or die(mysql_error());
  
}
require_once('dbconnect.php');
$result = mysql_query("select * from enrolled_details where course_id='$a'") or die(mysql_error());
while ($row = mysql_fetch_array($result)) {
    $id_no = $row['id_no'];

    $result1 = mysql_query("select name from registered where id_no='$id_no'") or die(mysql_error());
    if ($row1 = mysql_fetch_array($result1)) {
        echo "<div class='enroll'>" . $id_no . "   " . $row1['name'] . "<a href=facindex.php?page=show&id=".$a."&to_remove=" . $id_no . ">   Remove </a></div><br>\n";
    } 
}
?>