<div class="errors"><ul>
<?php require 'dbconnect.php';

$empty_string_init = "\"    \" ";

$sun_count   = 0;   
$mon_count   = 0;   
$tue_count   = 0;
$wed_count   = 0;
$thu_count   = 0;
$fri_count   = 0;
$sat_count   = 0;

if(array_key_exists('save', $_POST))
{
$sun1_start  = ( $_POST['sun_time1_start'] != "" ) ? $_POST['sun_time1_start'] : $empty_string_init;
$sun1_end    = ( $_POST['sun_time1_end']   != "" ) ? $_POST['sun_time1_end']   : $empty_string_init;
$sun2_start  = ( $_POST['sun_time2_start'] != "" ) ? $_POST['sun_time2_start'] : $empty_string_init;
$sun2_end    = ( $_POST['sun_time2_end']   != "" ) ? $_POST['sun_time2_end']   : $empty_string_init;
   
$mon1_start  = ( $_POST['mon_time1_start'] != "" ) ? $_POST['mon_time1_start'] : $empty_string_init;
$mon1_end    = ( $_POST['mon_time1_end']   != "" ) ? $_POST['mon_time1_end']   : $empty_string_init;
$mon2_start  = ( $_POST['mon_time2_start'] != "" ) ? $_POST['mon_time2_start'] : $empty_string_init;
$mon2_end    = ( $_POST['mon_time2_end']   != "" ) ? $_POST['mon_time2_end']   : $empty_string_init;

$tue1_start  = ( $_POST['tue_time1_start'] != "" ) ? $_POST['tue_time1_start'] : $empty_string_init;
$tue1_end  = ( $_POST['tue_time1_end']     != "" ) ? $_POST['tue_time1_end']   : $empty_string_init;
$tue2_start  = ( $_POST['tue_time2_start'] != "" ) ? $_POST['tue_time2_start'] : $empty_string_init;
$tue2_end  = ( $_POST['tue_time2_end']     != "" ) ? $_POST['tue_time2_end']   : $empty_string_init;

$wed1_start  = ( $_POST['wed_time1_start'] != "" ) ? $_POST['wed_time1_start'] : $empty_string_init;
$wed1_end  = ( $_POST['wed_time1_end']     != "" ) ? $_POST['wed_time1_end']   : $empty_string_init;
$wed2_start  = ( $_POST['wed_time2_start'] != "" ) ? $_POST['wed_time2_start'] : $empty_string_init;
$wed2_end  = ( $_POST['wed_time2_end']     != "" ) ? $_POST['wed_time2_end']   : $empty_string_init;

$thu1_start  = ( $_POST['thu_time1_start'] != "" ) ? $_POST['thu_time1_start'] : $empty_string_init;
$thu1_end  = ( $_POST['thu_time1_end']     != "" ) ? $_POST['thu_time1_end']   : $empty_string_init;
$thu2_start  = ( $_POST['thu_time2_start'] != "" ) ? $_POST['thu_time2_start'] : $empty_string_init;
$thu2_end  = ( $_POST['thu_time2_end']     != "" ) ? $_POST['thu_time2_end']   : $empty_string_init;

$fri1_start  = ( $_POST['fri_time1_start'] != "" ) ? $_POST['fri_time1_start'] : $empty_string_init;
$fri1_end  = ( $_POST['fri_time1_end']     != "" ) ? $_POST['fri_time1_end']   : $empty_string_init;
$fri2_start  = ( $_POST['fri_time2_start'] != "" ) ? $_POST['fri_time2_start'] : $empty_string_init;
$fri2_end  = ( $_POST['fri_time2_end']     != "" ) ? $_POST['fri_time2_end']   : $empty_string_init;

$sat1_start  = ( $_POST['sat_time1_start'] != "" ) ? $_POST['sat_time1_start'] : $empty_string_init;
$sat1_end    = ( $_POST['sat_time1_end']   != "" ) ? $_POST['sat_time1_end']   : $empty_string_init;
$sat2_start  = ( $_POST['sat_time2_start'] != "" ) ? $_POST['sat_time2_start'] : $empty_string_init;
$sat2_end    = ( $_POST['sat_time2_end']   != "" ) ? $_POST['sat_time2_end']   : $empty_string_init;

$index = array(
                $sun1_start , $sun1_end , $sun2_start , $sun2_end ,
                $mon1_start , $mon1_end , $mon2_start , $mon2_end ,
                $tue1_start , $tue1_end , $tue2_start , $tue2_end ,
                $wed1_start , $wed1_end , $wed2_start , $wed2_end ,
                $thu1_start , $thu1_end , $thu2_start , $thu2_end ,
                $fri1_start , $fri1_end , $fri2_start , $fri2_end ,
                $sat1_start , $sat1_end , $sat2_start , $sat2_end
              );
$day   = array ($sun_count , $mon_count , $tue_count , $wed_count , $thu_count , $fri_count , $sat_count);

$i=0;   //  for index array = 7 * 4 = 28 
$j=0;   //  for day array   = 7

while ( $i  < 28 )
{
    //if scheule one has class
    if (( $index[$i] != $empty_string_init ) and ($index[$i+1] != $empty_string_init)) 
    {
        $day[$j]++;
    }

    //if scheule two has class
    if (( $index[$i+2] != $empty_string_init ) and ($index[$i+3] != $empty_string_init)) 
    {
        $day[$j]++;
    }
    
    $i = $i + 4;
    $j = $j + 1 ;
}

$sun_count = $day[0];
$mon_count = $day[1];
$tue_count = $day[2];
$wed_count = $day[3];
$thu_count = $day[4];
$fri_count = $day[5];
$sat_count = $day[6];

echo "<br>";

$sun = "Sunday";
$mon = "Monday";
$tue = "Tuesday";
$wed = "Wednesday";
$thu = "Thursday";
$fri = "Friday";
$sat = "Saturday";

$c_id   = $_POST['courseID'];
$c_nm   = $_POST['Name'];
$fac_id = $_POST['FacultyID'];
$st_dt  = $_POST['StartDate'];
$fn_dt  = $_POST['FinishDate'];

//checking if the course has been already registered or not
$query = "SELECT *
          FROM course_details
          WHERE course_id = '$c_id' 
         ";
$result = mysql_query($query) ;
$row    = mysql_fetch_array($result);

//if entry in table fails : i.e. course already exists or already registered
if (is_null($row))
{
    echo $c_nm . "  (   " .$c_id . "    )   " .     "<br><li>Not already registered</li>";
    echo "<br>For registering go to ADD COURSE";
}
else
{
    //updating course_details
    $query_cd = "   
                UPDATE course_details   
                SET course_name='$c_nm', id_no='$fac_id',starting_date = '$st_dt' , finishing_date = '$fn_dt'
                WHERE course_id='$c_id';
                ";
    $result_cd = mysql_query($query_cd);
    if (!$result_cd)
    {
        echo "Error in updating course_details";
    }
    else
    {
        //updating course_schedule
       
        //for Sunday
        $weekday = $sun;
        $c = $sun_count;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$sun1_start',time1_end='$sun1_end',time2_start='$sun2_start',time2_end='$sun2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Monday
        $weekday = $mon;
        $c       = $mon_count ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$mon1_start',time1_end='$mon1_end',time2_start='$mon2_start',time2_end='$mon2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Tuesday
        $weekday = $tue;
        $c       = $tue_count ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$tue1_start',time1_end='$tue1_end',time2_start='$tue2_start',time2_end='$tue2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Wednesday
        $weekday = $wed;
        $c       = $wed_count ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$wed1_start',time1_end='$wed1_end',time2_start='$wed2_start',time2_end='$wed2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Thursday
        $weekday = $thu;
        $c       = $thu_count  ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$thu1_start',time1_end='$thu1_end',time2_start='$thu2_start',time2_end='$thu2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Friday
        $weekday = $fri;
        $c = $fri_count ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$fri1_start',time1_end='$fri1_end',time2_start='$fri2_start',time2_end='$fri2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Saturday
        $weekday = $sat;
        $c       = $sat_count;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$sat1_start',time1_end='$sat1_end',time2_start='$sat2_start',time2_end='$sat2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
    }
    
    
}  

unset($_POST['save']);
    
} 

if (array_key_exists('load', $_POST))
{
    $course_id = $_POST['courseID'];
    //echo $course_id;
    
    $query =    "
                SELECT *
                FROM course_details
                WHERE course_id='$course_id'
                ";
    $result = mysql_query($query);
    
    $query_mon  =   "
                    SELECT time1_start , time1_end , time2_start , time2_end
                    FROM course_schedule
                    WHERE course_id='$course_id' AND day='Monday'
                ";
    $result_mon = mysql_query($query_mon);
    
    $row_mon    = mysql_fetch_array($result_mon);
    
    $query_tue  =   "
                    SELECT time1_start , time1_end , time2_start , time2_end
                    FROM course_schedule
                    WHERE course_id='$course_id' AND day='Tuesday'
                ";
    $result_tue = mysql_query($query_tue);
    
    $row_tue    = mysql_fetch_array($result_tue);
    
    $query_wed  =   "
                    SELECT time1_start , time1_end , time2_start , time2_end
                    FROM course_schedule
                    WHERE course_id='$course_id' AND day='Wednesday'
                ";
    $result_wed = mysql_query($query_wed);
    $row_wed    = mysql_fetch_array($result_wed);
    
    $query_thu  =   "
                    SELECT time1_start , time1_end , time2_start , time2_end
                    FROM course_schedule
                    WHERE course_id='$course_id' AND day='Thursday'
                ";
    $result_thu = mysql_query($query_thu);
    $row_thu    = mysql_fetch_array($result_thu);
    
    $query_fri  =   "
                    SELECT time1_start , time1_end , time2_start , time2_end
                    FROM course_schedule
                    WHERE course_id='$course_id' AND day='Friday'
                ";
    $result_fri = mysql_query($query_fri);
    $row_fri    = mysql_fetch_array($result_fri);
    
    $query_sat  =   "
                    SELECT time1_start , time1_end , time2_start , time2_end
                    FROM course_schedule
                    WHERE course_id='$course_id' AND day='Saturday'
                ";
    $result_sat = mysql_query($query_sat);
    $row_sat    = mysql_fetch_array($result_sat);
    
    $query_sun  =   "
                    SELECT time1_start , time1_end , time2_start , time2_end
                    FROM course_schedule
                    WHERE course_id='$course_id' AND day='Sunday'
                ";
    $result_sun = mysql_query($query_sun);
    $row_sun    = mysql_fetch_array($result_sun);
    
    if ( $row = mysql_fetch_array($result) )
    {
        
    
    


?>
</ul>
</div>
<br><br><br>
<h1>Edit Course </h1>

<form name="add" action="#" method="post">
    <fieldset>
    <div id="left">
  
        <div class="field">
             <label>Course ID</label> 
             <?php 
                        $query = "
                                    SELECT course_id  
                                    FROM  course_details
                                    WHERE course_id='$course_id'
                                    ";
                        $result1 = mysql_query($query) or die(mysql_error());                     
             ?>
             
             <select name="courseID"  value="<?php echo $course_id;?>" >
             <?php                      
                        while ($row1 = mysql_fetch_array($result1))
                        {
                              //$val = $row1['course_id'] ;
                              //<?php if ($course_id == $val ) echo 'selected';
                              echo "<option  value=".$row1['course_id']."> ". $row1['course_id'] ."  </option>";
                        }
             ?>
             </select> 
             <input id=" load "  type="submit" name="load" class="Submit" value="Load"  />
             <br>    
        </div>
        
        <br>
        
        <div class="field">
             <label>Course Name</label> 
             <input type="text" name="Name" value="<?php echo $row['course_name'];?>" />

        </div>
        
        <br>
              
        <div class="field">
             <label>Faculty ID</label> 
              
             
              
              <?php
                        $f_id = $row['id_no'];
                        
                        $query_fn =     "
                                        SELECT name
                                        FROM registered
                                        WHERE id_no = '$f_id'
                                        ";
                        $result_fn = mysql_query($query_fn);
                        $row_fn    = mysql_fetch_array($result_fn);
                        
                        $f_nm = $row_fn['name'];
                        
                        $query_f = "
                                    SELECT id ,name  
                                    FROM  faculty f , registered r
                                    WHERE id = id_no AND id != '$f_id'
                                    ";
                        
                        $result_f = mysql_query($query_f) or die(mysql_error());
                       
                        ?>
             
             <select name="FacultyID" >
                <?php
                        echo "<option value=".$f_id."> ". $f_nm ."  </option>";
                        while ($row_f = mysql_fetch_array($result_f))
                        {
                              echo "<option value=".$row_f['id']."> ". $row_f['name'] ."  </option>";
                        }
                 ?>
             </select>
             
        </div>
        
        
        <br>
        
        
        <div class="field">
             <label>Start Date</label> 
             <input type="Text" name="StartDate" value="<?php echo $row['starting_date'];?>" class="datepicker"> 
        </div>
        
        
        <br>
        
        
        <div class="field">
             <label>Finish Date</label> 
             <input type="Text" name="FinishDate" value="<?php echo $row['finishing_date'];?>" class="datepicker"> 
        </div>
        
        
        <br>
      </div>
      <br> 
     
      
      
      <div >
          <p> Schedule for the whole week </p>
          <br>
          
          
          <div class="field">
            
             <label>DAY </label> 
             
             <label> FROM </label>
             &nbsp;&nbsp;&nbsp;<label1></label1>
             <label>TO<label>
          </div>
          
      <br>
          
      
          <div class="field">
            
             <label>Monday </label> 
             <input type="Text" class="time1"  name="mon_time1_start" value="<?php echo $row_mon['time1_start'];?>" id="Mon1"> 
             <input type="Text" class="time1"  name="mon_time1_end" value="<?php echo $row_mon['time1_end'];?>"> 
             <input id="Mon" type="button" value="  +1 Slot  " onclick="show(this ,'mon');" /><br>
          </div>
          <div id="mon" class="field">
              <label></label>
             <input type="Text" class="time1" name="mon_time2_start" id="mon_sec_st" value="<?php echo $row_mon['time2_start'];?>"> 
             <input type="Text" class="time1"  name="mon_time2_end"  id="mon_sec_fn" value="<?php echo $row_mon['time2_end'];?>"> <br>
            
      </div>
      <br>  <label></label><label1></label1>
            <input type="button" name="copy_slots" id="copy_slots" value=" Copy for other slots " onclick="copy();"/>
      <br><br>
      <div class="field">
            
             <label>Tuesday </label> 
             <input type="Text" name="tue_time1_start" value="<?php echo $row_tue['time1_start'];?>" class="time1"> 
             <input type="Text"  class="time1" name="tue_time1_end" value="<?php echo $row_tue['time1_end'];?>"> 
             <input id="Tue" type="button" value="  +1 Slot  " onclick="show(this , 'tue');" /> 
             </div>
          <div id="tue" class="field">          
              <label></label>
             <input type="Text" class="time1"  name="tue_time2_start" id="tue_sec_st" value="<?php echo $row_tue['time2_start'];?>"> 
             <input type="Text"  class="time1" name="tue_time2_end" id="tue_sec_fn" value="<?php echo $row_tue['time2_end'];?>"> 
            
          </div>
      <br>
      <div class="field">
            
             <label>Wednesday </label> 
             <input type="Text" class="time1"  name="wed_time1_start" value="<?php echo $row_wed['time1_start'];?>"> 
             <input type="Text"  class="time1" name="wed_time1_end" value="<?php echo $row_wed['time1_end'];?>"> 
             <input id="Wed" type="button" value="  +1 Slot  " onclick="show(this ,'wed');" /> 
            </div>
          <div id="wed" class="field"> 
            
            <label></label>
              
            <input type="Text"  class="time1" name="wed_time2_start" id="wed_sec_st" value="<?php echo $row_wed['time2_start'];?>">
            <input type="Text"  class="time1" name="wed_time2_end" id="wed_sec_fn" value="<?php echo $row_wed['time2_end'];?>">
            
          </div>
      <br>
      <div class="field">
            <label>Thursday </label>
            <input type="Text"  class="time1" name="thu_time1_start" value="<?php echo $row_thu['time1_start'];?>">
            <input type="Text"  class="time1" name="thu_time1_end" value="<?php echo $row_thu['time1_end'];?>">
             <input id="Thu" type="button" value="  +1 Slot  " onclick="show(this , 'thu');" />
             </div>
          <div id="thu" class="field"> 
             <label></label>
            <input type="Text" class="time1"  name="thu_time2_start" id="thu_sec_st" value="<?php echo $row_thu['time2_start'];?>">
            <input type="Text"  class="time1" name="thu_time2_end" id="thu_sec_fn" value="<?php echo $row_thu['time2_end'];?>">
          </div>
      <br>
      <div class="field">
            <label>Friday </label>
            <input type="Text"  class="time1" name="fri_time1_start" value="<?php echo $row_fri['time1_start'];?>">
            <input type="Text" class="time1"  name="fri_time1_end" value="<?php echo $row_fri['time1_end'];?>">
            <input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'fri');" />
            </div>
          <div id="fri" class="field"> 
            <label></label>
              <input type="Text"  class="time1" name="fri_time2_start" id="fri_sec_st" value="<?php echo $row_fri['time2_start'];?>">
            <input type="Text"  class="time1" name="fri_time2_end" id="fri_sec_fn" value="<?php echo $row_fri['time2_end'];?>"><br>
          </div>
      
      </table>    
      </div>
      <br>
      <div class="field">
            
             <label>Saturday </label> 
             <input type="Text"  class="time1" name="sat_time1_start" value="<?php echo $row_sat['time1_start'];?>"> 
             <input type="Text"  class="time1" name="sat_time1_end" value="<?php echo $row_sat['time1_end'];?>"> 
             <input id="clickMe"  class="time1" type="button" value="  +1 Slot  " onclick="show(this ,'sat');" /><br>
          </div>
          <div id="sat" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sat_time2_start" id="sat_sec_st" value="<?php echo $row_sat['time2_start'];?>"> 
             <input type="Text"  class="time1" name="sat_time2_end"  id="sat_sec_fn" value="<?php echo $row_sat['time2_end'];?>"> <br>
            
      </div>
      <br>  
      <div class="field">
            
             <label>Sunday </label> 
             <input type="Text" class="time1"  name="sun_time1_start" value="<?php echo $row_sun['time1_start'];?>"> 
             <input type="Text"  class="time1" name="sun_time1_end" value="<?php echo $row_sun['time1_end'];?>"> 
             <input id="clickMe" type="button" value="  +1 Slot  " onclick="show(this ,'sun');" /><br>
          </div>
          <div id="sun" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sun_time2_start" id="sun_sec_st" value="<?php echo $row_sun['time2_start'];?>"> 
             <input type="Text"  class="time1" name="sun_time2_end"  id="sun_sec_fn" value="<?php echo $row_sun['time2_end'];?>"> <br>
            
      </div>
        <br><br>
      <div class="wrapper">
            <label></label>
            
            <label><input type="submit" name="save" class="Submit" /></label>
            <label><input type="submit" name="cancel" value="Cancel" class="submit" /></label>
            
      </div>
    </fieldset>


    <br><br><br><br>
</form>
    <br><br><br><br>
    <?php } }
    else
    {
        
    ?>
    <h1>Edit Course </h1>

<form name="add" action="#" method="post">
    <fieldset>
    <div id="left">
  
        <div class="field">
             <label>Course ID</label> 
             <?php 
                        $query = "
                                    SELECT course_name,course_id  
                                    FROM  course_details
                                    ";
                        $result = mysql_query($query) or die(mysql_error());                     
             ?>
             
             <select name="courseID" >
             <?php                      
                        while ($row = mysql_fetch_array($result))
                        {
                              echo "<option value=".$row['course_id']."> ". $row['course_id']."->". $row['course_name'] ."  </option>";
                        }
             ?>
             </select> 
             <input id=" load "  type="submit" name="load" class="Submit" value="Load"  />
             <br>    
        </div>
        
        <br>
        
        <div class="field">
             <label>Course Name</label> 
             <input type="text" name="Name" value="<?php echo $row['course_name']?>" />
                
             
        </div>
        
        <br>
              
        <div class="field">
             <label>Faculty ID</label> 
             <input type="text" name="FacultyID" value="" /> 
        </div>
        
        
        <br>
        
        
        <div class="field">
             <label>Start Date</label> 
             <input type="Text" name="StartDate" value="" class="datepicker"> 
        </div>
        
        
        <br>
        
        
        <div class="field">
             <label>Finish Date</label> 
             <input type="Text" name="FinishDate" value="" class="datepicker"> 
        </div>
        
        
        <br>
      </div>
      <br> 
     
      
      
      <div >
          <p> Schedule for the whole week </p>
          <br>
          
          
          <div class="field">
            
             <label>DAY </label> 
             
             <label> FROM </label>
             &nbsp;&nbsp;&nbsp;<label1></label1>
             <label>TO<label>
          </div>
          
      <br>
          
      
          <div class="field">
            
             <label>Monday </label> 
             <input type="Text" class="time1"  name="mon_time1_start" value="" id="Mon1"> 
             <input type="Text" class="time1"  name="mon_time1_end" value=""> 
             <input id="Mon" type="button" value="  +1 Slot  " onclick="show(this ,'mon');" /><br>
          </div>
          <div id="mon" class="field">
              <label></label>
             <input type="Text" class="time1" name="mon_time2_start" id="mon_sec_st" value=""> 
             <input type="Text" class="time1"  name="mon_time2_end"  id="mon_sec_fn" value=""> <br>
            
      </div>
      <br>  <label></label><label1></label1>
            <input type="button" name="copy_slots" id="copy_slots" value=" Copy for other slots " onclick="copy();"/>
      <br><br>
      <div class="field">
            
             <label>Tuesday </label> 
             <input type="Text" name="tue_time1_start" value="" class="time1"> 
             <input type="Text"  class="time1" name="tue_time1_end" value=""> 
             <input id="Tue" type="button" value="  +1 Slot  " onclick="show(this , 'tue');" /> 
             </div>
          <div id="tue" class="field">          
              <label></label>
             <input type="Text" class="time1"  name="tue_time2_start" id="tue_sec_st" value=""> 
             <input type="Text"  class="time1" name="tue_time2_end" id="tue_sec_fn" value=""> 
            
          </div>
      <br>
      <div class="field">
            
             <label>Wednesday </label> 
             <input type="Text" class="time1"  name="wed_time1_start" value=""> 
             <input type="Text"  class="time1" name="wed_time1_end" value=""> 
             <input id="Wed" type="button" value="  +1 Slot  " onclick="show(this ,'wed');" /> 
            </div>
          <div id="wed" class="field"> 
            
            <label></label>
              
            <input type="Text"  class="time1" name="wed_time2_start" id="wed_sec_st" value="">
            <input type="Text"  class="time1" name="wed_time2_end" id="wed_sec_fn" value="">
            
          </div>
      <br>
      <div class="field">
            <label>Thursday </label>
            <input type="Text"  class="time1" name="thu_time1_start" value="">
            <input type="Text"  class="time1" name="thu_time1_end" value="">
             <input id="Thu" type="button" value="  +1 Slot  " onclick="show(this , 'thu');" />
             </div>
          <div id="thu" class="field"> 
             <label></label>
            <input type="Text" class="time1"  name="thu_time2_start" id="thu_sec_st" value="">
            <input type="Text"  class="time1" name="thu_time2_end" id="thu_sec_fn" value="">
          </div>
      <br>
      <div class="field">
            <label>Friday </label>
            <input type="Text"  class="time1" name="fri_time1_start" value="">
            <input type="Text" class="time1"  name="fri_time1_end" value="">
            <input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'fri');" />
            </div>
          <div id="fri" class="field"> 
            <label></label>
              <input type="Text"  class="time1" name="fri_time2_start" id="fri_sec_st" value="">
            <input type="Text"  class="time1" name="fri_time2_end" id="fri_sec_fn" value=""><br>
          </div>
      
      </table>    
      </div>
      <br>
      <div class="field">
            
             <label>Saturday </label> 
             <input type="Text"  class="time1" name="sat_time1_start" value=""> 
             <input type="Text"  class="time1" name="sat_time1_end" value=""> 
             <input id="clickMe"  class="time1" type="button" value="  +1 Slot  " onclick="show(this ,'sat');" /><br>
          </div>
          <div id="sat" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sat_time2_start" id="sat_sec_st" value=""> 
             <input type="Text"  class="time1" name="sat_time2_end"  id="sat_sec_fn" value=""> <br>
            
      </div>
      <br>  
      <div class="field">
            
             <label>Sunday </label> 
             <input type="Text" class="time1"  name="sun_time1_start" value=""> 
             <input type="Text"  class="time1" name="sun_time1_end" value=""> 
             <input id="clickMe" type="button" value="  +1 Slot  " onclick="show(this ,'sun');" /><br>
          </div>
          <div id="sun" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sun_time2_start" id="sun_sec_st" value=""> 
             <input type="Text"  class="time1" name="sun_time2_end"  id="sun_sec_fn" value=""> <br>
            
      </div>
        <br><br>
      <div class="wrapper">
            <label></label>
            
            <label><input type="submit" name="save" class="Submit" /></label>
            <label><input type="submit" name="cancel" value="Cancel" class="submit" /></label>
            
      </div>
    </fieldset>
    </form>
<?php }  ?>